FROM projectatomic/atomicapp:0.1.12

MAINTAINER Dharmit Shah <dshah@redhat.com>

LABEL io.projectatomic.nulecule.providers="docker" \
      io.projectatomic.nulecule.specversion="0.0.2"

ADD /Nulecule /Dockerfile /application-entity/
ADD /artifacts /application-entity/artifacts
