FROM projectatomic/atomicapp:0.4.0

MAINTAINER Red Hat, Inc. <container-tools@redhat.com>

LABEL io.projectatomic.nulecule.specversion=0.0.2 \
      io.projectatomic.nulecule.providers=""kubernetes,docker,openshift"

ADD /Nulecule /Dockerfile /application-entity/
ADD /artifacts /application-entity/artifacts
