FROM projectatomic/atomicapp:0.4.3

MAINTAINER Jeroen van Meeuwen <vanmeeuwen@kolabsys.com>

LABEL io.projectatomic.nulecule.specversion="0.0.2" \
      io.projectatomic.nulecule.providers="kubernetes,docker,openshift"

ADD /Nulecule gpl-3.0.txt /application-entity/
ADD /artifacts /application-entity/artifacts
